# Generated by Django 2.2.1 on 2019-06-01 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190601_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='quiz',
        ),
    ]
