# Generated by Django 2.2.1 on 2019-06-01 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0004_auto_20190601_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='level',
            field=models.CharField(choices=[('EA', 'Easy'), ('MI', 'Middle'), ('HI', 'High')], default='MI', max_length=2),
        ),
        migrations.AddField(
            model_name='history',
            name='quiz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.Sentence'),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
