# Generated by Django 2.2.1 on 2019-06-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20190601_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='src',
            field=models.CharField(default='', max_length=200),
        ),
    ]
